baseurl      = "https://gonkdev.github.io"
title        = "GonkDev"
languageCode = "en-us"
theme        = "hello-friend"
paginate     = 10

[params]
  dateform        = "Jan 1, 20023"
  dateformShort   = "Jan 1"
  dateformNum     = "2023-01-01"
  dateformNumTime = "2023-01-01 15:04"

  # Subtitle for home
  homeSubtitle = "A simple blog to track my progress as I move through a tech career."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"


  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"